---
chart_key: fph_bta # a unique identifier for the chart being added, string.
data_source: ph_readings # the SQL table to read historical data from. The data source must have a timestamp, pioreactor_unit, and experiment column, along with a numeric column to plot (see below), string.
data_source_column: ph_reading # the column in data_source to read and display, string.
title: pH # title on the chart, string
mqtt_topic: vernier_fph_bta/ph_reading # a truncated MQTT topic to read live data from - stripped of the pioreactor/<unit>/<experiment> part. Ex: co2_readings/ppm if the entire MQTT topic is pioreactor/<unit>/<experiment>/co2_readings/ppm, string.
source: app
payload_key: # (Optional) If the MQTT topic is json blobs, use the payload_key to retrieve the data from the blob, string.
y_axis_label: pH # the y-axis label, string
interpolation: stepAfter # (Optional) the interpolation to use between points, default is stepAfter, string.
y_axis_domain: [0,14] # (Optional) specify a starting y-axis domain. Must be an array, like [0.0, 0.5].
y_transformation: # (Optional) an inline JS function to transform the y data. Default is the identity function, string.
lookback: 10000 # Not described in docs
fixed_decimals: 1 # How many decimals to display, integer.
down_sample: false # (Optional) A boolean to down-sample the data points from the server or not.
